In [ ]:
import pandas as pd  #pandas is a library used to manipulate data in a tabular setup 
import numpy as np #numpy is a mathematical python lib used for operating on matrices and arrays while providing extensive functions to work on said arrays and matrices.

In [ ]:
from numpy import array
from sklearn.preprocessing import Normalizer  #Skitlearn is a machine learning lib used for supervised and unsupervised learning
from keras.activations import sigmoid #Keras is a deeplearning library that powers machine learning projects
from keras.losses import mse
from numpy.random import uniform

Hyperparameters

In [ ]:
batch_size=2

Dataset

In [ ]:
#We pass in our data in key value pairs...we can also pass ina csv file using the pd.read_csv
data={'Day 1':[30,40,50,20,15,60],'Day 2':[40,50,20,15,60,70],
      'Day 3':[50,20,15,60,70,50],'Target':[20,15,60,70,50,40]}

In [ ]:
#we frame our dataset to enable us to manipulate it 
dataset=pd.DataFrame(data)

In [ ]:
dataset

Day 1  Day 2  Day 3  Target
0     30     40     50      20
1     40     50     20      15
2     50     20     15      60
3     20     15     60      70
4     15     60     70      50
5     60     70     50      40

In [ ]:
X=dataset.drop('Target',axis=1)# we seperate our inputs from our target by dropping the target column and storing the input in a var
y=dataset['Target']# we store our target column in a var 

In [ ]:
X# We display our inputs

Day 1  Day 2  Day 3
0     30     40     50
1     40     50     20
2     50     20     15
3     20     15     60
4     15     60     70
5     60     70     50

We now have our inputs but the input values require normalization in order for them to be used in our A.N.N. 
Thus, we use a normalization function to convert the values into numbers within the range of 1 and -1 as these values

In [ ]:
X_norm = Normalizer(norm='max').fit_transform(X)

In [ ]:
X_norm

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

In [ ]:
array(y)

array([20, 15, 60, 70, 50, 40])

In [ ]:
np.reshape(array(y),(1,-1))

array([[20, 15, 60, 70, 50, 40]])

In [ ]:
y_norm=Normalizer(norm='max').fit_transform(np.reshape(array(y),(1,-1)))

In [ ]:
y_norm

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

ANN From Scratch

In [ ]:
weight_1=array([[.2,.1],[.3,.1],[.2,.1]])
weight_2=array([[.5],[.1]])

In [ ]:
# weight_1=uniform(-1,1,(3,2)) #shape 3 by 2
# weight_2=uniform(-1,1,(2,1))

In [ ]:
weight_1

array([[0.2, 0.1],
       [0.3, 0.1],
       [0.2, 0.1]])

In [ ]:
weight_2

array([[0.5],
       [0.1]])

In [ ]:
X_norm[0:batch_size]

array([[0.6, 0.8, 1. ],
       [0.8, 1. , 0.4]])

In [ ]:
output_1=X_norm[0:batch_size]@weight_1
output_1

array([[0.56, 0.24],
       [0.54, 0.22]])

In [ ]:
act_output=sigmoid(output_1).numpy()
act_output

array([[0.63645254, 0.55971365],
       [0.63181242, 0.55477924]])

In [ ]:
pred_output=act_output@weight_2
pred_output=np.reshape(pred_output,(1,-1))
pred_output

array([[0.37419764, 0.37138413]])

Mean Squared Error

In [ ]:
y_true=y_norm[0][0:batch_size]
y_pred=pred_output


In [ ]:
y_true

array([0.28571429, 0.21428571])

In [ ]:
error_k=mse(y_true,y_pred).numpy()

In [ ]:
error_j=error*(weight_2*(act_output[0][0]*(1-act_output[0][0])))
error_j=np.reshape(error_j,(1,2))





In [ ]:
weight2_n=weight_2+0.003*error_k*y_true
weight2_n
weight1_n=weight_2+0.003*error_j*act_output
weight1_n

array([[0.50000359, 0.50000063],
       [0.10000356, 0.10000063]])